export const COUNTRIES = [
  "Thailand",
  "United States",
  "United Kingdom",
  "Singapore",
  "Japan",
  "South Korea",
  "China",
  "Australia",
  "Germany",
  "France",
  "India",
  "Vietnam",
  "Malaysia",
  "Indonesia",
  "Philippines",
] as const;
